### ISSUE TITLE
config "command:" in docker-compose possibel?

### ISSUE THREAD

**Issue by BPMspace** [msoap/shell2http#55]
HI 

i have the following docker-compose file , but don't get multiple commds to run ...

```
version: '3.7'

networks:
 proxy-net:
   external: true
   
services:
  shell2http_swarm_master:
    image: bpmspace/docker_bpmspace_base:shell2http
    **command: /bin/sh "/app/shell2http -form /date date /ps "ps aux" /form 'echo $v_from, $v_to'"**
    hostname: shell2http_swarm_master
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.shell2http_swarm_master.rule=Host(`shell2http_swarm_master.bpmspace.net`)
        - traefik.http.services.shell2http_swarm_master-service.loadbalancer.server.port=8080
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - proxy-net   

  shell2http_swarm_node:
    image: bpmspace/docker_bpmspace_base:shell2http
    hostname: shell2http_swarm_node
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.shell2http_swarm_node.rule=Host(`shell2http_swarm_node.bpmspace.net`)
        - traefik.http.services.shell2http_swarm_node-service.loadbalancer.server.port=8080
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    networks:
      - proxy-net   
```
The error messages is " task: non-zero exit (1)"

When I start the service again without the "command" line it works! BUT i only have 1 command "/date" since my Dockerfile is your test.Dockerfile

Do you have any hint how to "add" new commands via compose file? My image is created via GITHUB -> webhooks -> dockerhub ... so it is no option to add all the commands i need in in the Dockerfile and in a DockerSwarm the "build:" in docker-compose is not supported .... 

thanks rob

PS when i try to execute the command in the sh of the container it tells me: 

/ # ./app/shell2http -form /date date /ps "ps aux" /form 'echo $v_from, $v_to'
2020/01/05 15:30:40 register: /date (date)
2020/01/05 15:30:40 register: /ps (ps aux)
2020/01/05 15:30:40 register: /form (echo $v_from, $v_to)
2020/01/05 15:30:40 register: / (index page)
2020/01/05 15:30:40 listen tcp :8080: bind: address already in use

**Comment by BPMspace** [comment]
Think i got it myself - your entrypoint is already "/app/shell2http" -  so the command line must be only 
...
command: '/date date /top "top | head -10"'
...

**Comment by BPMspace** [comment]
this is not working - container stops 
command: ' /date date /top "top | head -10" **-form** /form "echo $v_from, $v_to"'

this does not stop the container - but does not echo the variables just gives an "," back
command: '**-form** /date date /top "top | head -10"  /form "echo $v_from, $v_to"'

http://shell2http_swarm_master.mydomain.net/form?from=10&to=76987
nor
http://shell2http_swarm_master.mydomain.nett/form?v_from=10&v_to=76987

![image](https://user-images.githubusercontent.com/5494549/71782779-54ca2300-2fde-11ea-9b3b-1bb7e5580f48.png)


any hint?

**Comment by msoap** [comment]
Hi, about

```
**command: /bin/sh "/app/shell2http -form /date date /ps "ps aux" /form 'echo $v_from, $v_to'"**
```

why not:
```
/bin/sh -c "/app/shell2http..."
```
?

**Comment by msoap** [comment]
I'm created small `docker-compose.yml` with `command:` field:

```
version: "3.7"

services:
  shell2http_service:
    image: msoap/shell2http
    container_name: shell2http_service
    command: "/date date /ps 'ps aux'"
    ports:
      - "8080:8080"

```

working well `/date` and `/ps` requests
